export const blueprintData = {
    ASG: [
        {
            type: 'vpc',
            dimensions: {
                width: 1553,
                height: 636,
            },
            handleBounds: {},
            computedPosition: {
                x: -777.0679569698721,
                y: -1211.3589869669183,
                z: 0,
            },
            selected: false,
            dragging: false,
            resizing: false,
            initialized: true,
            data: {
                name: 'example-vpc',
                cidr: '10.0.0.0/16',
                publicsubnet: 2,
                privatesubnet: 3,
                azs: ['us-east-1c', 'us-east-1a'],
                nat_gateway: true,
            },
            events: {},
            id: '0',
            position: {
                x: -777.0679569698721,
                y: -1211.3589869669183,
            },
            label: 'vpc node',
            style: {
                width: '1553px',
                height: '635.9879131342452px',
            },
            isParent: true,
        },
        {
            parentNode: '3',
            type: 'privatesubnet',
            dimensions: {
                width: 200,
                height: 300,
            },
            handleBounds: {},
            computedPosition: {
                x: -293.6599157487084,
                y: -1061.8143990921951,
                z: 2,
            },
            selected: false,
            dragging: false,
            resizing: false,
            initialized: true,
            data: {},
            events: {},
            id: '1',
            position: {
                x: 369.40804122116367,
                y: 75.54458787472328,
            },
            label: 'privatesubnet node',
            expandParent: true,
            style: {
                width: '177px',
                height: '247px',
            },
        },
        {
            parentNode: '0',
            type: 'asg',
            dimensions: {
                width: 641,
                height: 419,
            },
            handleBounds: {},
            computedPosition: {
                x: -663.0679569698721,
                y: -1137.3589869669183,
                z: 1,
            },
            selected: false,
            dragging: false,
            resizing: false,
            initialized: true,
            data: {
                min_size: 1,
                max_size: 3,
                desired_capacity: 2,
                image_id: 'ami-053b0d53c279acc90',
                instance_type: 't2.micro',
                user_data: 'echo test',
            },
            events: {},
            id: '3',
            position: {
                x: 114,
                y: 74,
            },
            label: 'asg node',
            expandParent: true,
            style: {
                width: '641px',
                height: '419px',
            },
            isParent: true,
        },
        {
            parentNode: '6',
            type: 'publicsubnet',
            dimensions: {
                width: 200,
                height: 300,
            },
            handleBounds: {},
            computedPosition: {
                x: 333.31067145684324,
                y: -1059.8029236807351,
                z: 2,
            },
            selected: false,
            dragging: false,
            resizing: false,
            initialized: true,
            data: {},
            events: {},
            id: '5',
            position: {
                x: 308.46080852014256,
                y: 43.5560632861833,
            },
            label: 'publicsubnet node',
            expandParent: true,
            style: {
                width: '121px',
                height: '292px',
            },
        },
        {
            parentNode: '0',
            type: 'alb',
            dimensions: {
                width: 593,
                height: 389,
            },
            handleBounds: {},
            computedPosition: {
                x: 24.849862936700674,
                y: -1103.3589869669183,
                z: 1,
            },
            selected: false,
            dragging: false,
            resizing: false,
            initialized: true,
            data: {},
            events: {},
            id: '6',
            position: {
                x: 801.9178199065727,
                y: 108,
            },
            label: 'alb node',
            expandParent: true,
            isParent: true,
            style: {
                width: '593px',
                height: '388.89484860665726px',
            },
        },
        {
            parentNode: '6',
            type: 'publicsubnet',
            dimensions: {
                width: 200,
                height: 300,
            },
            handleBounds: {},
            computedPosition: {
                x: 76.10331874390693,
                y: -1056.842809607057,
                z: 2,
            },
            selected: false,
            dragging: false,
            resizing: false,
            initialized: true,
            data: {},
            events: {},
            id: '2',
            position: {
                x: 51.25345580720625,
                y: 46.51617735986133,
            },
            label: 'publicsubnet node',
            expandParent: true,
        },
        {
            type: 'privatesubnet',
            dimensions: {
                width: 200,
                height: 300,
            },
            handleBounds: {},
            computedPosition: {
                x: -556.7704637799641,
                y: -1055.3589869669183,
                z: 2,
            },
            selected: false,
            dragging: false,
            resizing: false,
            initialized: true,
            parentNode: '3',
            data: {},
            events: {},
            id: '8',
            position: {
                x: 106.29749318990798,
                y: 82,
            },
            label: 'privatesubnet node',
            expandParent: true,
        },
    ],
};
